services:
  mysql:
    image: mysql:8.0
    container_name: feed_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
      MYSQL_DATABASE: feed_system
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7
    container_name: feed_redis
    restart: always
    ports:
      - "6380:6379"

  meilisearch:
    image: getmeili/meilisearch:v1.14
    container_name: feed_meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-masterKey}
      MEILI_ENV: development
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data

volumes:
  meilisearch_data:
